spring.application.name=application-service

# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# Turning off JPA-config to use Hibernate directly
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
