spring.application.name=decision-service

# Server
server.port=8090

# Database
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# Camunda
camunda.bpm.auto-deployment-enabled=true
camunda.bpm.database.schema-update=true
camunda.bpm.admin-user.id=admin
camunda.bpm.admin-user.password=admin
camunda.bpm.generic-properties.properties.historyTimeToLive=30

# Turning off JPA-config to use Hibernate directly
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
